#!/usr/bin/env python3
"""Write docs/FRESHNESS.md: when each reference file was last reviewed.

Status rules (ArcGIS ships Pro/Enterprise releases roughly twice a year):
  current   reviewed within 180 days
  aging     181-365 days
  stale     over 365 days
  undated   no 'Last reviewed' date (content from v1.0; review and date it)

Usage:
  python tools/freshness_report.py            # write docs/FRESHNESS.md
  python tools/freshness_report.py --check    # exit 1 if anything is stale or undated
"""
from __future__ import annotations

import sys
from datetime import date

from _common import ROOT, reference_files

AGING, STALE = 180, 365


def status(days: int | None) -> str:
    if days is None:
        return "undated"
    if days > STALE:
        return "stale"
    if days > AGING:
        return "aging"
    return "current"


def main() -> int:
    today = date.today()
    rows, counts = [], {"current": 0, "aging": 0, "stale": 0, "undated": 0}
    for rf in reference_files():
        days = (today - rf.reviewed).days if rf.reviewed else None
        st = status(days)
        counts[st] += 1
        rows.append((st, rf.rel, rf.reviewed.isoformat() if rf.reviewed else "—",
                     f"{days}" if days is not None else "—"))
    order = {"stale": 0, "undated": 1, "aging": 2, "current": 3}
    rows.sort(key=lambda r: (order[r[0]], r[1]))
    icon = {"current": "🟢", "aging": "🟡", "stale": "🔴", "undated": "⚪"}

    out = [
        "# Content freshness",
        "",
        "Generated by `python tools/freshness_report.py` and refreshed monthly by the",
        "*Freshness* workflow. A file's date comes from the `Last reviewed:` line in its header.",
        "",
        f"**{counts['current']} current · {counts['aging']} aging · "
        f"{counts['stale']} stale · {counts['undated']} undated**",
        "",
        "| Status | File | Last reviewed | Days |",
        "|---|---|---|---|",
    ]
    for st, rel, rev, days in rows:
        out.append(f"| {icon[st]} {st} | `{rel}` | {rev} | {days} |")
    out += [
        "",
        "## How to review a file",
        "1. Check each version-specific fact against the current Esri page it cites.",
        "2. Fix what changed; add new parameters or behaviour with the release that introduced them.",
        "3. Update the header to `Last reviewed: YYYY-MM-DD (Pro x.y / Enterprise x.y docs)`.",
        "4. Open a PR — CI lints the file and this report updates on the next run.",
        "",
    ]
    (ROOT / "docs" / "FRESHNESS.md").write_text("\n".join(out), encoding="utf-8")
    print(f"docs/FRESHNESS.md written: {counts}")
    if "--check" in sys.argv and (counts["stale"] or counts["undated"]):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
